[package]
name = "ui-tui"
version = "0.3.0"
description = "Stable foundation release with adaptive trust propagation, P2P analytics, and Android integration."
edition = "2021"

[dependencies]
ratatui = "0.27"
crossterm = "0.27"