[package]
name = "truth_core"
version = "0.3.0"
description = "Minimal Android version of Truth Core"
edition = "2021"

[workspace]

[lib]
name = "truth_core"
path = "src/android_minimal.rs"
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }

# Android-specific dependencies
[target.'cfg(target_os = "android")'.dependencies]
getrandom = { version = "0.2", features = ["std"] }
