[target.aarch64-linux-android]
linker = "aarch64-linux-android29-clang"
ar = "llvm-ar"

[target.x86_64-linux-android]
linker = "x86_64-linux-android29-clang"
ar = "llvm-ar"

[env]
CC_aarch64_linux_android = "aarch64-linux-android29-clang"
CXX_aarch64_linux_android = "aarch64-linux-android29-clang++"
CC_x86_64_linux_android = "x86_64-linux-android29-clang"
CXX_x86_64_linux_android = "x86_64-linux-android29-clang++"