name: Build, Test, and Publish Android Library

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Android target and tools
        run: |
          rustup target add aarch64-linux-android
          cargo install cargo-ndk

      - name: Set up Android SDK and NDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: 26.1.10909125

      - name: Build library
        run: ./scripts/build-android.sh

      - name: Run unit tests
        run: cargo test --test android_verify -- --nocapture

      - name: Upload libtruth_core.so
        uses: actions/upload-artifact@v4
        with:
          name: libtruth_core.so
          path: target/**/libtruth_core.so
          retention-days: 7

  publish-and-notify:
    needs: build-android
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}

    steps:
      - name: Download built library
        uses: actions/download-artifact@v4
        with:
          name: libtruth_core.so
          path: dist/

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: android-lib-${{ github.run_number }}
          name: Android Core Build ${{ github.run_number }}
          files: dist/**/libtruth_core.so
          body: |
            ✅ Built and tested libtruth_core.so for Android.
            Triggered from commit: ${{ github.sha }}

      - name: Trigger client sync
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: ekwator/truth-android-client
          event-type: update-libtruth
          client-payload: '{"artifact_url": "https://github.com/${{ github.repository }}/releases/download/android-lib-${{ github.run_number }}/libtruth_core.so"}'
