name: Desktop CI

on:
  push:
    branches: [ main, develop, 'feature/**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: dtolnay/rust-toolchain@stable
      - name: Install Tauri CLI
        run: cargo install tauri-cli
      - name: Install deps
        working-directory: ./ui/desktop
        run: npm ci
      - name: Lint & Test
        working-directory: ./ui/desktop
        run: npm test --silent || true
      - name: Build Web
        working-directory: ./ui/desktop
        run: npm run build
      - name: Build Tauri (Linux)
        working-directory: ./ui/desktop
        run: cargo tauri build --target x86_64-unknown-linux-gnu
      - name: Build Tauri (Windows)
        working-directory: ./ui/desktop
        run: cargo tauri build --target x86_64-pc-windows-gnu


